### ISSUE TITLE
Damage Calculation does not work for group attacks if a dice value is set 

### ISSUE THREAD

**Issue by V3rotti** [fantasycalendar/FoundryVTT-MinionManager#3]
When the damage is set to a value like "1d4" damage, rolling for damage results in an error
![image](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/56869989/49115061-ea83-424b-8b30-37798497dcb8)

**Comment by Haxxer** [comment]
Group attacks get multiplied by the number of attackers - so you want this to be 5d4?

**Comment by V3rotti** [comment]
i thought it would be the result of 1d4 multiplied by 5, but i have no real intended way of calculation by now.
I was just stumbling onto this when i tested group attacks and used a premade actor for the attacks.
the sample zombie in the ruleset has a fixed damage too, so thats how it seems to be intended. maybe, when setting an attack as a group attack, there could be a hint, that damage values have to be digits, so other users will no stumble into this and think its bugged.

**Comment by Haxxer** [comment]
Fixed in 1.0.4
