### ISSUE TITLE
Overkill Feature

### ISSUE THREAD

**Issue by CepheiA2** [fantasycalendar/FoundryVTT-MinionManager#4]
Browser: Chrome
FoundryVTT v11 build 311
Module Version: Last Release.

Hi,
I have some issues with the overkill feature: the feature is enabled on the module options and the token/sheet is marked as a minion, as are the ones next to it.

But when my player character hit with an attack  or deal damage to it, no message/pop-up appears indicating the possibility of overkill.

I'm using the Midi Qol module, maybe it could influence this dynamic? 
or am i missing somenthing?

I would be happy to receive a response on this matter, cause i really like this module and MCDM rules for combat encounters.

**Comment by Haxxer** [comment]
1. Could you please check the console to make sure that there are no errors
2. Please take a screenshot of the current settings of Minion Manager
3. Please export and upload your MidiQOL settings - you can do so from the workflow settings in MidiQOL

**Comment by CepheiA2** [comment]
1. i've found this error, but i don't know if is correlated
midi-qol |  hooked function for hook midi-qol.preDamageRollComplete TypeError: Cannot read properties of null (reading 'name')
    at midiqol.js:121:51
    at Array.filter (<anonymous>)
    at Object.fn (midiqol.js:119:6)
    at hookCall (utils.js:4184:16)
    at asyncHooksCallAll (utils.js:4143:10)
    at Workflow._next (workflow.js:676:11)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    
2.
![screenshot-options](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/85868381/17b73c13-ef53-4406-87b2-0b46dd71a462)

3. i didnt' fount the importer, i've uploaded some screen
![Screenshot 2023-10-16 190814](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/85868381/ded4ea4b-01a9-4c16-a25b-cb46baffc919)
![Screenshot 2023-10-16 1908142](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/85868381/9aeea258-9b42-4c1d-898d-20737cee62ff)

**Comment by Haxxer** [comment]
One of the tokens on the map do not have an NPC associated with it, breaking my script. Try double clicking on each token on that scene until you find the one that doesn't open the sheet, and then delete it or fix it.

**Comment by CepheiA2** [comment]
i've tried, but every token is associated with a character sheet, i tried
with other tokens and sheet too

**Comment by CepheiA2** [comment]
Following your advice, i tried something else, and i found that in
every scene i've created before installing the module, the overkill feature
doesn't work, and works on scenes created after the module is installed.

**Comment by Haxxer** [comment]
Should be fixed in 1.0.5, please check and close ticket if the patch was a success :)

**Comment by CepheiA2** [comment]
Everything seems to work. Thanks
