### ISSUE TITLE
Use Minion XP Rates for Minion NPCs 

### ISSUE THREAD

**Issue by chipperme** [fantasycalendar/FoundryVTT-MinionManager#5]
Feature request! 🙇 The dnd5e system gives each NPC an XP value based on its CR. That relationship's built on that one table from the DMG.

Minions have a CR, but their XP values are described with a different table ("Minion Encounter Building", on page 13 of _Flee, Mortals!_). I've experimented to see if I can do something on my end—using DAE effects to change the XP value found at `system.details.xp.value`—but I've gotten stuck. That XP value shown on the sheet hasn't changed and the amount awarded by automated modules for awarding XP is still based on that DMG table. I'm guessing `xp.value` behaves like a method, not a property, dependent on `system.details.cr`?

Between the stickiness of `xp.value` and how the preview packet does _not_ include this Minion XP table, I understand if this is too big an ask!

**Comment by Haxxer** [comment]
If it is not publicly available, I cannot add this information.
