### ISSUE TITLE
Link initiative roll?

### ISSUE THREAD

**Issue by avportia** [fantasycalendar/FoundryVTT-MinionManager#8]
Hey, this was just what I needed, but is there a way to link the initiative roll for all of the marked creatures so that I only need to roll once? As it is, I can right-click on the shield and mark five tokens, for example, with a 1, but unless I'm missing something they all roll initiative separately, resulting in all different results. Then I have to manually change each of them to one number before starting the battle.

**Comment by Haxxer** [comment]
The design of the module should make it so that you only have 1 entity in the combat tracker if added through the numbers. If you are seeing more than 1, you most likely have a module conflict.

**Comment by Haxxer** [comment]
Like so:
![image](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/12858387/a44b61cc-83d9-46e7-90b1-100d2ed52885)

**Comment by avportia** [comment]
Huh. Well I'm glad it's supposed to work that way. This is what I'm doing: I select all the creatures, I right-click to reveal the hud, left click on the swords to put them in combat, then right-click again and tag them with #1. Result:
![image](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/151247416/3457f8ce-e0f4-4f66-8613-e230ad9e8421)
![image](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/151247416/032474ae-e6d0-4949-a64f-99bcd9979dfc)

**Comment by Haxxer** [comment]
Do not put them into combat first, remove them and add them only through the numbers.

The documentation doesn't mention adding them to the tracker first:
https://github.com/fantasycalendar/FoundryVTT-MinionManager?tab=readme-ov-file#group-initiative

**Comment by avportia** [comment]
Very good. That solves it. Thank you for the fast reply! 
![image](https://github.com/fantasycalendar/FoundryVTT-MinionManager/assets/151247416/886eb45f-8df6-4b5e-aa4f-b9a55e98e56e) What a great module. This is a godsend.
